# https://velog.io/@win-luck/Springboot-Multi-DataSourcereaderDB-writerDB-%EC%84%A4%EC%A0%95%ED%95%98%EA%B3%A0-%EB%9D%BC%EC%9A%B0%ED%8C%85%ED%95%98%EA%B8%B0

spring:
  datasource:
    writer:
      driver-class-name: org.postgresql.Driver
      read-only: false
      jdbc-url: jdbc:postgresql://localhost:5432/leanmysuru
      username: postgres
      password: postgres
      pool-name: HikariCP-Writer
    reader:
      driver-class-name: org.postgresql.Driver
      read-only: true
      jdbc-url: jdbc:postgresql://localhost:5432/leanmysuru
      username: postgres
      password: postgres
      pool-name: HikariCP-Reader
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

