# if you want to use independent config,
# exclude config profile and redefine properties here
spring:
  profiles:
    include:
      - usecase-api-service
      - rds-adapter-out
      - security-adapter-in
