spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            scope: # google API의 범위 값
              - profile
              - email
            redirect-uri: http://localhost:8088/login/oauth2/code/google